<!doctype html><meta charset=utf-8><body style="margin:0;background:#0d1117;color:#f0f6fc;font:14px/1.6 -apple-system,Segoe UI,sans-serif"><div style="width:880px;margin:0 auto;padding:20px"><style>a{color:#4493f8;text-decoration:none}table{border-collapse:collapse;display:block;width:max-content;max-width:100%;overflow:auto}td{border:1px solid #3d444d;padding:6px 13px}img{max-width:100%}code{background:#262c36;padding:.2em .4em;border-radius:6px}h2{border-bottom:1px solid #3d444d;padding-bottom:.3em}img[alt=private]{vertical-align:-1px;margin-right:3px}</style><table width="100%">
<tr><td><picture>
  <source media="(prefers-color-scheme: dark)" srcset="file:///D:/GitHub/personal/hector-ae21/profile/assets/banner-dark.svg">
  <img alt="What I work on: backend, packages, data, security, moodle, research" src="file:///D:/GitHub/personal/hector-ae21/profile/assets/banner-dark.svg" width="100%">
</picture></td></tr>
<tr><td align="right"><a href="https://github.com/hector-ae21/hector-ae21/blob/main/profile/pages/packages.md">Packages</a> / <a href="https://github.com/hector-ae21/hector-ae21/blob/main/profile/pages/moodle.md">Moodle</a> / <a href="https://github.com/hector-ae21/hector-ae21/blob/main/profile/pages/stack.md">Stack</a></td></tr>
<tr><td align="right"><a href="https://www.linkedin.com/in/hector-arrechea/">LinkedIn</a> / <a href="https://orcid.org/0009-0008-0090-3927">ORCID</a> / <a href="https://www.npmjs.com/~hector21">npm</a> / <a href="https://github.com/didactika">Didactika</a> / <a href="https://github.com/resilientmq">ResilientMQ</a></td></tr>
<tr><td align="right"><picture><source media="(prefers-color-scheme: dark)" srcset="file:///D:/GitHub/personal/hector-ae21/profile/assets/lock-dark.svg"><img alt="private" src="file:///D:/GitHub/personal/hector-ae21/profile/assets/lock-dark.svg" height="11"></picture> <a href="https://github.com/hector-ae21/CIBINT">CIBINT</a></td></tr>
<tr><td align="right"><picture><source media="(prefers-color-scheme: dark)" srcset="file:///D:/GitHub/personal/hector-ae21/profile/assets/lock-dark.svg"><img alt="private" src="file:///D:/GitHub/personal/hector-ae21/profile/assets/lock-dark.svg" height="11"></picture> <a href="https://github.com/mmasias/TDHector">TDHector</a> / <a href="https://github.com/hector-ae21/http-response-client">http-response-client</a> / <a href="https://github.com/hector-ae21/moodle-local_digitalta">digitalta-plugin</a> / <a href="https://github.com/hector-ae21/moodle-theme_digitalta">digitalta-theme</a> / <a href="https://github.com/hector-ae21/Cache-Db">Cache-Db</a></td></tr>
</table><h2>Stack</h2><table>
<tr><td valign="top"><sub><b>Languages</b></sub></td><td><sub><code>TypeScript</code> <code>JavaScript</code> <code>PHP</code> <code>Python</code> <code>Java</code> <code>C / C++</code></sub></td></tr>
<tr><td valign="top"><sub><b>Backend</b></sub></td><td><sub><code>Node.js</code> <code>Express</code> <code>Fastify</code> <code>Hono</code> <code>Next.js</code></sub></td></tr>
<tr><td valign="top"><sub><b>Data</b></sub></td><td><sub><code>PostgreSQL</code> <code>MongoDB</code> <code>Prisma</code> <code>Sequelize</code> <code>Mongoose</code></sub></td></tr>
<tr><td valign="top"><sub><b>Messaging</b></sub></td><td><sub><code>RabbitMQ</code> <code>AMQP</code> <code>Event-driven design</code> <code>Dead-letter queues</code></sub></td></tr>
<tr><td valign="top"><sub><b>Platforms</b></sub></td><td><sub><code>Moodle</code> <code>Docker</code> <code>GitHub Actions</code> <code>Jest</code> <code>Testcontainers</code></sub></td></tr>
<tr><td valign="top"><sub><b>Security</b></sub></td><td><sub><code>OSINT</code> <code>Threat intelligence</code> <code>MITRE ATT&amp;CK</code> <code>OPSEC</code></sub></td></tr>
</table></div>