/**
 * The profile page itself: github.com/<user> renders this file.
 *
 * There is no <h1>. GitHub prints the account's name and bio in the sidebar
 * beside this column, so a heading here would be the third copy of the same two
 * lines — and the banner is the second.
 */

import { escapeXml } from "../text.mjs";
import { HeaderTable } from "./header.mjs";
import { StackTable } from "./stack-table.mjs";

export class ReadmePage {
  constructor({ profile, data, links, log, stamp }) {
    this.profile = profile;
    this.data = data;
    this.links = links;
    this.log = log;
    this.stamp = stamp;
    this.header = new HeaderTable({ profile, data, links, log });
  }

  render() {
    const p = this.profile;
    const c = p.copy;

    // Two charts, not four. What I write in and what I write it on, side by
    // side; the owner breakdown was the repository one grouped a level up, and
    // the yearly one was the weekly chart below at a coarser resolution. Both
    // said the same thing twice.
    const grid = this.links.chartGrid([
      [{ base: "languages", alt: c.metrics.languages }, { base: "perrepo", alt: c.metrics.perrepo }],
    ]);

    return `<!--
  GENERATED FILE — DO NOT EDIT.
  Rendered from profile/data/content.json + the GitHub API by
  scripts/generate-profile.mjs, on a schedule. Edit the JSON, not this.
  Last generated: ${this.stamp}
-->

${p.opening ? `<p align="center"><em>${escapeXml(p.opening)}</em></p>\n` : ""}
${this.header.render(this.links.picture("banner", p.bannerAlt))}

## ${p.about.heading}

${p.about.points.map((point) => `- ${point}`).join("\n")}

${this.#roles(p.about.roles)}

## ${c.metrics.heading}

${this.links.picture("stats", "Profile statistics")}

${grid}

${this.links.picture("activity", c.metrics.activity)}

<sub>${c.metrics.note}</sub>

## ${p.stack.heading}

${StackTable.render(p.stack)}

---

${this.#footer(c)}
`;
  }

  #roles(roles = []) {
    if (!roles.length) return "";
    const width = 100 / roles.length;
    const cells = roles.map(({ role, name, url }) => `<td width="${width}%" align="center">
<sub>${escapeXml(role)}</sub><br>
<strong><a href="${url}">${escapeXml(name)}</a></strong>
</td>`).join("\n");
    return `<table width="100%">\n<tr>\n${cells}\n</tr>\n</table>`;
  }

  #footer(c) {
    const user = this.profile.user;
    return `<p align="center">
  <em>${escapeXml(c.footer)}</em><br>
  <a href="${user.linkedin}">LinkedIn</a> ·
  <a href="${user.orcid}">ORCID</a> ·
  <a href="${user.npm}">npm</a> ·
  <a href="${this.links.profile}">GitHub</a><br>
  <sub>${escapeXml(user.location)} · updated ${this.stamp} · generated by <a href="${this.links.generator}">generate-profile.mjs</a></sub>
</p>`;
  }
}
